# Generated by Django 5.2 on 2025-04-02 18:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ai_processing', '0001_initial'),
        ('classroom_integration', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignmentdraft',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='classroom_integration.assignment'),
        ),
        migrations.AddField(
            model_name='textchunk',
            name='material',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='classroom_integration.material'),
        ),
    ]
