# Generated by Django 5.2 on 2025-04-03 01:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0002_initial'),
        ('classroom_integration', '0003_alter_assignment_options_alter_course_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Chunk',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('embedding_vector', models.BinaryField(blank=True, null=True)),
                ('chunk_index', models.PositiveIntegerField()),
                ('metadata', models.JSONField(blank=True, default=dict)),
            ],
            options={
                'ordering': ['document', 'chunk_index'],
            },
        ),
        migrations.RenameField(
            model_name='assignmentdraft',
            old_name='generated_content',
            new_name='ai_generated_content',
        ),
        migrations.RenameField(
            model_name='assignmentdraft',
            old_name='user_edits',
            new_name='prompt_used',
        ),
        migrations.RemoveField(
            model_name='assignmentdraft',
            name='retrieved_context',
        ),
        migrations.RemoveField(
            model_name='assignmentdraft',
            name='status',
        ),
        migrations.AddField(
            model_name='assignmentdraft',
            name='is_final',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentdraft',
            name='submission_timestamp',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentdraft',
            name='submitted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='assignmentdraft',
            name='user_edited_content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='assignmentdraft',
            name='relevant_chunks',
            field=models.ManyToManyField(blank=True, related_name='used_in_drafts', to='ai_processing.chunk'),
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_text', models.TextField()),
                ('processed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('page_count', models.PositiveIntegerField(default=0)),
                ('material', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='classroom_integration.material')),
            ],
        ),
        migrations.AddField(
            model_name='chunk',
            name='document',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='chunks', to='ai_processing.document'),
        ),
        migrations.DeleteModel(
            name='TextChunk',
        ),
    ]
