# Generated by Django 5.2 on 2025-04-04 00:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0003_chunk_and_more'),
        ('classroom_integration', '0004_alter_material_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='material',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='document', to='classroom_integration.assignmentmaterial'),
        ),
    ]
