# Generated by Django 5.2 on 2025-04-03 01:40

import django.core.serializers.json
import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AgentTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task_type', models.CharField(choices=[('email_draft', 'Email Draft'), ('web_search', 'Web Search'), ('weather', 'Weather Information'), ('question', 'General Question')], max_length=50)),
                ('prompt', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('response', models.TextField(blank=True, null=True)),
                ('metadata', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agent_tasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='EmailDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=255)),
                ('to_recipients', models.TextField()),
                ('cc_recipients', models.TextField(blank=True)),
                ('bcc_recipients', models.TextField(blank=True)),
                ('ai_generated_content', models.TextField()),
                ('user_edited_content', models.TextField(blank=True)),
                ('final_content', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('ready', 'Ready to Send'), ('sent', 'Sent'), ('failed', 'Failed to Send')], default='draft', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('gmail_message_id', models.CharField(blank=True, max_length=255)),
                ('agent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='email_drafts', to='aiAgent.agenttask')),
            ],
        ),
        migrations.CreateModel(
            name='SearchResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('snippet', models.TextField()),
                ('url', models.URLField(max_length=2048)),
                ('position', models.PositiveIntegerField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('agent_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='search_results', to='aiAgent.agenttask')),
            ],
            options={
                'ordering': ['position'],
            },
        ),
    ]
