# Generated by Django 5.2 on 2025-04-03 01:40

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom_integration', '0002_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='assignment',
            options={'verbose_name': 'Assignment', 'verbose_name_plural': 'Assignments'},
        ),
        migrations.AlterModelOptions(
            name='course',
            options={'verbose_name': 'Course', 'verbose_name_plural': 'Courses'},
        ),
        migrations.AlterModelOptions(
            name='material',
            options={'verbose_name': 'Material', 'verbose_name_plural': 'Materials'},
        ),
        migrations.AlterField(
            model_name='assignment',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='google_id',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='assignment',
            name='status',
            field=models.CharField(choices=[('New', 'New'), ('Syncing', 'Syncing'), ('Processing', 'Processing'), ('MaterialsReady', 'Materials Ready'), ('GeneratingDraft', 'Generating Draft'), ('DraftReady', 'Draft Ready'), ('UserReviewing', 'User Reviewing'), ('GeneratingPDF', 'Generating PDF'), ('Submitting', 'Submitting'), ('Submitted', 'Submitted'), ('Error', 'Error')], default='New', max_length=20),
        ),
        migrations.AlterField(
            model_name='course',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='course',
            name='google_id',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='file_type',
            field=models.CharField(choices=[('GOOGLE_DRIVE', 'Google Drive'), ('LINK', 'Web Link'), ('YOUTUBE', 'YouTube Video'), ('FORM', 'Google Form'), ('Unknown', 'Unknown')], default='Unknown', max_length=20),
        ),
        migrations.AlterField(
            model_name='material',
            name='google_drive_file_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='google_id',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='material',
            name='google_link',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='material',
            name='processing_status',
            field=models.CharField(choices=[('Pending', 'Pending'), ('Downloading', 'Downloading'), ('Downloaded', 'Downloaded'), ('Processing', 'Processing'), ('Chunking', 'Chunking'), ('Embedding', 'Embedding'), ('Processed', 'Processed'), ('Error', 'Error')], default='Pending', max_length=20),
        ),
        migrations.AlterUniqueTogether(
            name='assignment',
            unique_together={('google_id', 'course')},
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('google_id', 'owner')},
        ),
        migrations.AlterUniqueTogether(
            name='material',
            unique_together={('google_id', 'assignment')},
        ),
    ]
