# Generated by Django 5.2 on 2025-04-04 00:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ai_processing', '0004_alter_document_material'),
        ('classroom_integration', '0004_alter_material_unique_together_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Material',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='google_link',
        ),
        migrations.RemoveField(
            model_name='assignment',
            name='last_synced',
        ),
        migrations.RemoveField(
            model_name='course',
            name='description',
        ),
        migrations.RemoveField(
            model_name='course',
            name='google_id',
        ),
        migrations.RemoveField(
            model_name='course',
            name='last_synced',
        ),
    ]
